[input]
base_dir = "./"

[output]
results_dir = "results"
out_file = "out_{run}.txt"
err_file = "err_{run}.txt"

[dependencies]
add_k_vals_pl = "../apps/MCScanX-1.0.0/downstream_analyses/add_ka_and_ks_to_collinearity.pl"

[cores]
p = 8                  # the maximum number of processors to use for an individual task instance
auto_allocate_processors = true # automatically determine the maximum number of processors available and how many to use

[parameters]
alpha = 0.05           # for p-value filtering
l2FC_thresh = 1         # for l2FC filtering
frag_length_mean = 200 # for kallisto quant
frag_length_std = 20   # for kallisto quant

# All pangenes to use (will construct)
[pangene]
[pangene.Pangene] # [pangene.PANGENE_NAME]
grp_file = "../pangene_test/synOG.grp_melt"
pangene_fastas_dir = "../sra_data/all/"
redundancy_thresh = 0.98 # by how much to reduce redunandant genes in the pangene
max_diff_r = 0.01
ks_threshold_pairs = [["97103_v3", "XG0526"]] # genomes to use to calculate the median Ks threshold

# Ready for analysis (all preconstructed pangenes and single-reference genomes)
# If a pangene already exists, it can be placed here! (.reduced_map and .fa.gz)
[reference]
[reference.Cultivated] # [reference.REFERENCE_NAME]
annotation_file = "../sra_data/base4/97103_v3/97103_v3.gff3.gz"
cds_fasta = "../sra_data/base4/97103_v3/97103_v3_cds.fa.gz"

[reference.Wild]
annotation_file = "../sra_data/base4/XG0486/XG0486.gff3.gz"
cds_fasta = "../sra_data/base4/XG0486/XG0486_cds.fa.gz"

[run]
[run.10DAP]
use = {"pangene" = ["Pangene"], "reference" = ["Cultivated", "Wild"]} # which references to use
conditions = ["S1G1T1P10D", "S1G2T1P10D"]
sample_dir = "data/samples"
samples = [
    "S1G1T1P10D_Rep1_RS.fq.gz",
    "S1G1T1P10D_Rep2_RS.fq.gz",
    "S1G2T1P10D_Rep1_RS.fq.gz",
    "S1G2T1P10D_Rep2_RS.fq.gz",
]

[run.18DAP]
use = {"pangene" = ["Pangene"], "reference" = ["Cultivated", "Wild"]} # which references to use
conditions = ["S1G1T1P18D", "S1G2T1P18D"]
sample_dir = "data/samples"
samples = [
    "S1G1T1P18D_Rep1_RS.fq.gz",
    "S1G1T1P18D_Rep2_RS.fq.gz",
    "S1G2T1P18D_Rep1_RS.fq.gz",
    "S1G2T1P18D_Rep2_RS.fq.gz",
]

[run.26DAP]
use = {"pangene" = ["Pangene"], "reference" = ["Cultivated", "Wild"]} # which references to use
conditions = ["S1G1T1P26D", "S1G2T1P26D"]
sample_dir = "data/samples"
samples = [
    "S1G1T1P26D_Rep1_RS.fq.gz",
    "S1G1T1P26D_Rep2_RS.fq.gz",
    "S1G2T1P26D_Rep1_RS.fq.gz",
    "S1G2T1P26D_Rep2_RS.fq.gz",
]

[run.34DAP]
use = {"pangene" = ["Pangene"], "reference" = ["Cultivated", "Wild"]} # which references to use
conditions = ["S1G1T1P34D", "S1G2T1P34D"]
sample_dir = "data/samples"
samples = [
    "S1G1T1P34D_Rep1_RS.fq.gz",
    "S1G1T1P34D_Rep2_RS.fq.gz",
    "S1G2T1P34D_Rep1_RS.fq.gz",
    "S1G2T1P34D_Rep2_RS.fq.gz",
]
