[input]
base_dir = "./"
sample_dir = "data/samples" # TODO: move to run?
# genome_reference_file = "assembly/97103_v3_genome.fa"

[output]
results_dir = "results"
out_file = "out_{run}.txt"
err_file = "err_{run}.txt"

[parameters]
p = 8                  # the maximum number of processors to use for an individual task instance
auto_allocate_processors = false # automatically determine the maximum number of processors available and how many to use
alpha = 0.05           # for p-value filtering
l2FC_thresh = 1         # for l2FC filtering
frag_length_mean = 200 # for kallisto quant
frag_length_std = 20   # for kallisto quant

# All pangenes to use (will construct)
[pangene]
[pangene.Pangene] # [pangene.PANGENE_NAME]
grp_file = "../pangene_test/t2t-synOG-ID_97103_v3.grp"
pangene_fastas_dir = "../sra_data/all/"
redundancy_thresh = 0.98 # by how much to reduce redunandant genes in the pangene

# Ready for analysis (all preconstructed pangenes and single-reference genomes)
# If a pangene already exists, it can be placed here! (.reduced_map and .fa.gz)
[reference]
[reference.Cultivated]
annotation_file = "../sra_data/base4/97103_v3/97103_v3.gff3.gz"
cds_fasta = "../sra_data/base4/97103_v3/97103_v3_cds.fa.gz"

[reference.Wild]
annotation_file = "../sra_data/base4/XG0486/XG0486.gff3.gz"
cds_fasta = "../sra_data/base4/XG0486/XG0486_cds.fa.gz"


[run]
[run.10DAPtest]
use = {"pangene" = ["Pangene"], "reference" = ["Cultivated", "Wild"]} # which references to use
conditions = ["S1G1T1P10D", "S1G2T1P10D"]
samples = [
    "S1G1T1P10D_Rep1_RS.fq.gz",
    "S1G1T1P10D_Rep2_RS.fq.gz",
    "S1G2T1P10D_Rep1_RS.fq.gz",
    "S1G2T1P10D_Rep2_RS.fq.gz",
]


# [runs.10DAP]
# annotations = {Cultivated = "", Wild = "", Pangene = ""}
# references = {Cultivated = "../sra_data/base4/97103_v3/97103_v3_cds.fa.gz", Wild = "../sra_data/base4/XG0486/XG0486_cds.fa.gz", Pangene = ""}
# conditions = ["S1G1T1P10D", "S1G2T1P10D"]
# samples = [
#     "S1G1T1P10D_Rep1_RS.fq.gz",
#     "S1G1T1P10D_Rep2_RS.fq.gz",
#     "S1G2T1P10D_Rep1_RS.fq.gz",
#     "S1G2T1P10D_Rep2_RS.fq.gz",
# ]

# 18DAP = [
#     "S1G1T1P18D_Rep1_RS.fq.gz",
#     "S1G1T1P18D_Rep2_RS.fq.gz",
#     "S1G2T1P18D_Rep1_RS.fq.gz",
#     "S1G2T1P18D_Rep2_RS.fq.gz",
# ]
# 26DAP = [
#     "S1G1T1P26D_Rep1_RS.fq.gz",
#     "S1G1T1P26D_Rep2_RS.fq.gz",
#     "S1G2T1P26D_Rep1_RS.fq.gz",
#     "S1G2T1P26D_Rep2_RS.fq.gz",
# ]
# 34DAP = [
#     "S1G1T1P34D_Rep1_RS.fq.gz",
#     "S1G1T1P34D_Rep2_RS.fq.gz",
#     "S1G2T1P34D_Rep1_RS.fq.gz",
#     "S1G2T1P34D_Rep2_RS.fq.gz",
# ]
